-- ============================================
-- Migration: CRM, Leads, Email Campaigns & Secure Invites
-- ============================================

-- 1. SECURE USER INVITES
CREATE TABLE IF NOT EXISTS public.user_invites (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  email TEXT UNIQUE NOT NULL,
  role TEXT NOT NULL CHECK (role IN ('admin', 'writer', 'viewer')),
  created_by UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS for invites
ALTER TABLE public.user_invites ENABLE ROW LEVEL SECURITY;

-- Only admins can manage invites
CREATE POLICY "Admins can manage invites"
  ON public.user_invites FOR ALL USING (
    (SELECT role FROM profiles WHERE id = auth.uid()) = 'admin'
  );

-- Fix the trigger to use the invites table instead of trusting user metadata
CREATE OR REPLACE FUNCTION handle_new_user()
RETURNS TRIGGER AS $$
DECLARE
  invited_role TEXT;
BEGIN
  -- Check if there is an invite for this email
  SELECT role INTO invited_role FROM public.user_invites WHERE email = NEW.email;
  
  INSERT INTO public.profiles (id, email, full_name, role)
  VALUES (
    NEW.id,
    NEW.email,
    COALESCE(NEW.raw_user_meta_data->>'full_name', ''),
    COALESCE(invited_role, 'viewer') -- Default to viewer if no invite
  );

  -- Consume the invite
  DELETE FROM public.user_invites WHERE email = NEW.email;
  
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 2. CRM LEADS
CREATE TABLE IF NOT EXISTS public.leads (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL,
  email TEXT,
  phone TEXT,
  company TEXT,
  project_type TEXT, -- e.g., 'office', 'hospitality', 'retail'
  budget TEXT,
  message TEXT,
  ai_tags TEXT[] DEFAULT '{}', -- Tags generated by AI (e.g., 'high-budget', 'urgent')
  ai_intent TEXT, -- Processed intent ('buy_retail', 'wholesale_project')
  status TEXT DEFAULT 'new' CHECK (status IN ('new', 'contacted', 'qualified', 'lost', 'won')),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.leads ENABLE ROW LEVEL SECURITY;

-- Anyone can insert leads (public form)
CREATE POLICY "Anyone can submit leads"
  ON public.leads FOR INSERT WITH CHECK (true);

-- Admins and writers can view/manage leads
CREATE POLICY "Staff can manage leads"
  ON public.leads FOR ALL USING (
    (SELECT role FROM profiles WHERE id = auth.uid()) IN ('admin', 'writer')
  );

-- 3. EMAIL CAMPAIGNS
CREATE TABLE IF NOT EXISTS public.email_campaigns (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  title TEXT NOT NULL,
  subject TEXT NOT NULL,
  body_html TEXT NOT NULL,
  target_audience TEXT DEFAULT 'all', -- 'all', 'new_leads', 'qualified_leads'
  status TEXT DEFAULT 'draft' CHECK (status IN ('draft', 'scheduled', 'sent', 'failed')),
  sent_count INT DEFAULT 0,
  scheduled_for TIMESTAMPTZ,
  created_by UUID REFERENCES auth.users(id),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.email_campaigns ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Staff can manage email campaigns"
  ON public.email_campaigns FOR ALL USING (
    (SELECT role FROM profiles WHERE id = auth.uid()) IN ('admin', 'writer')
  );
